name: Generate Audio from MSCZ files
on: 
  workflow_dispatch:
   
env:
  REGISTRY: ghcr.io
jobs:
  generate-audio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Checkout scripts repo
        uses: actions/checkout@v3
        with:
          repository: jshethbright/musescore-part-sorter
          ref: 'release'
          path: './scripts'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Docker image
        run: |
          docker pull ghcr.io/jshethbright/musescore-headless-docker:latest

      - name: Generate audio
        run: |
          docker run --rm -v $(pwd):/input ghcr.io/jshethbright/musescore-headless-docker:latest

      - name: Sort audio
        run: |
          python scripts/partsorter.py "scores/" "partmap.yaml" "audio"
      - name: Prepare parts for Drive push
        run: |
          mkdir parts
          mv scores/parts ./
      - name: Push parts to Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.DRIVE_CREDS }}
          filename: parts/*/*
          folderId: ${{ secrets.FOLDERID }}
          overwrite: "true"
          mirrorDirectoryStructure: "true"