name: Generate PDFs from MSCZ files
on: push

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip os yaml argparse
    
      - name: Build Docker image
        run: |
          docker build -t musescore .

      - name: Generate PDFs
        run: |
          docker run --rm -v $(pwd):/input musescore

      - name: Sort PDFs
        run: |
          python scripts/partsorter.py "scores/" "partmap.yaml"
      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pdfs
          path: scores/parts/*