name: Generate PDFs from MSCZ files
on: 
  release:
   types:
      - published
env:
  REGISTRY: ghcr.io
jobs:
  generate-pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Checkout scripts repo
        uses: actions/checkout@v3
        with:
          repository: jshethbright/musescore-part-sorter
          ref: 'release'
          path: './scripts'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Docker image
        run: |
          docker pull ghcr.io/jshethbright/musescore-headless-docker:latest

      - name: Generate PDFs
        run: |
          docker run --rm -v $(pwd):/input ghcr.io/jshethbright/musescore-headless-docker:latest

      - name: Sort PDFs
        run: |
          python scripts/partsorter.py "scores/" "partmap.yaml"
      - name: Create artifact
        run: |
          zip -r scores/pdfs.zip scores/parts/*
      - name: Attach artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }} 
          asset_path: scores/pdfs.zip
          asset_name: pdfs.zip
          asset_content_type: application/zip
          tag_name: ${{ github.ref }}
      - name: Push parts to drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.DRIVE_CREDS }}
          filename: scores/parts/**
          folderId: ${{ secrets.FOLDERID }}
          overwrite: "true"